
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;


contract task3_1 {
    // Объявляем массив с именами людей, которые встают в очередь. Тип данных - строка. Доступ всем.
    string[] public namesOfPeople;


    constructor() public {
        require(tvm.pubkey() != 0, 101);
        require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();  
  }
  
// функция добавления в массив. Тип данных - строка.
function GetInLine(string name) public {
    namesOfPeople.push(name);
    tvm.accept();
    }

// Функция "Вызвать следующего". Нулевой элемент массива пропадает.
function callTheNext() public {
    // копируем индексы. значение первого становится равно второму, второго третьему и т.д Последний не изменится
    for(uint i = 0; i < namesOfPeople.length - 1; i++) {
        namesOfPeople[i] = namesOfPeople[i + 1];
    }
    //удаляем последний индекс.
    namesOfPeople.pop();
    tvm.accept();
    }
}